### ISSUE TITLE
1.0 Checklist

### ISSUE THREAD

**Issue by JerrySievert** [Esri/terraformer#138]
These are the features that need to be completed for 1.0 release.
- [x] refactor wkt parser to its own repo
- [x] refactor arcjson parser to its own repo
- [x] refactor rtree to its own repo
- [x] refactor geostore to its own repo
- [x] refactor stores to their own repos
- [x] remove deferred and use node style callbacks
- [x] #137 
- [x] #123 
- [x] terraformer github site
- [x] better documentation
- [x] bower integration
- [ ] make sure all samples work
- [ ] some better samples
- [ ] prepare blog posts
- [x] WE NEED A LOGO
- [x] additional index types
